### ISSUE TITLE
material styles in production

### ISSUE THREAD

**Issue by dweitz43** [spock123/angular2-webpack2-typescript2#1]
do you mind explaining a little about how your app is loading the material styles in production builds? I like the way you created the MdModule, I am trying to implement something similar in the material2 branch of the angular2-webpack-starter repo that this repo is based upon. 

Everything appears to work fine in development mode, but in production, I am having trouble trying to correctly load the material styles. I was able to get the tooltips working by using the CopyWebpackPlugin to copy the material assets from node_modules into the dist/assets directory during production builds, and then by loading the overlay.css from dist/assets as a stylesheet in the  head-config.common.js, so that it loads the individual stylesheet in index.html. 

I suppose it would be possible to use a similar method to load all of the individual material stylesheets, but I noticed that your repo is importing overlay.css from node_modules in the bootstrap.ts. I was not able to replicate that method successfully in the angular2-webpack-starter repo for production or development builds. Looking around your repo a little more, I couldn't really find anywhere else that would be including the other material styles, except maybe as part of the angular2-material import statements in vendor.ts? 

So I am a little bit confused as to how it is working so seamlessly and in such a clean way, without the need to explicitly import all the material styles. I would like to try to replicate this method in the angular2-webpack-starter repo, if you are able to provide any extra information about how exactly your repo is loading the styles so cleanly, I would definitely appreciate the help.

Just an idea I had, but I am not sure if it holds any substance or makes any sense: All of the components in the angular2-webpack-starter repo use the styleUrls property to define their stylesheet locations, while all of your components do not use this property. I am wondering if that might be playing a role in why the material styles aren't being applied?

**Comment by spock123** [comment]
Hey man, thanks for your input.
I am not home right now but let me take a look at it later today... 

Cheers

**Comment by dweitz43** [comment]
thanks for the quick response! i appreciate your efforts. just in case you are interested for reference, i have pushed my progress so far to my fork here: https://github.com/dweitz43/angular2-webpack-starter/tree/material2

**Comment by spock123** [comment]
Hi again, I'm gonna take a look at the things now, just one quick comment:

I'm importing the overlay.css file in my bootstrap to overcome a bug in _Material2 alpha 7-4._ It is definitely not something that should be needed once the final version comes out. The overlay.css is needed if you want to use _md-menu_ and _md-tooltip_ components.

You can read about it in the GETTING_STARTED document in the Material2-repo:

https://github.com/angular/material2/blob/master/GETTING_STARTED.md

Another note:

You can load css anywhere you like, but where you do, will determine which bundle it will be enrolled into. 

Anything imported from the _vendors.ts_ file will be bundled in the vendors bundle.

Anything imported from bootstrap.ts or other application files, will be bundle in the app.bundle. 

So it's really up to you where you want it. 
The serviceworker setup will make sure that only the bundle that has changed, will be updated in the browser cache, so if your styles don't change that often, put them in the vendors bundle. But if they do, put them in the app bundle... 

Also, notice I'm loading the Material fonts in the index.html.. I didn't want to download and import them in this repo, but maybe I should. I a real-world app I would definitely think about putting the icons into my build... 

Alright, be back later.. cheers

**Comment by spock123** [comment]
@dweitz43  so I cloned your repo, but i don't see any Material Design components? Is that the repo you would like to import and use the Material components?

**Comment by dweitz43** [comment]
@spock123 thanks for all this info. i do understand all of those items clearly, and i believe i am doing similar things to get the tooltips, icons/fonts loaded properly. i am also importing the components in vendor.browser.ts currently as well. if you clone my repo and switch to the material2 branch, you should find src/app/md.module.ts, in which i attempted to create an NgModule to export all of the material modules together in a similar fashion to how you did in your repo. I import the MdModule from that file inside src/app/app.module.ts. Then, the templates in src/app/app.component.ts, src/app/about/about.component.ts, and src/app/home/home.template.html all contain material components in the markup.

config/head-config.common.js is where i include the overlay.css that eventually gets included in index.html. I am currently using CopyWebpackPlugin in config/webpack.common.js to copy the material styles to the assets folder during the build so that i can include overlay.css in index.html, although it appears there should be a cleaner way, as it looks like you do not do this in your repo.

It looks like the production build does successfully roll the material styles into the vendor bundle, but for some reason, they are not being used when i run the production server. When I run the dev server, all of the styles and components appear to function correctly, without the need to copy anything from node_modules to assets as well.

**Comment by spock123** [comment]
@dweitz43  Ok sorry I didn't notice the branch, I was using the MASTER, hehehe.. Ok I'll check out the branch..

**Comment by dweitz43** [comment]
@spock123 haha no worries I thought that might have been the issue. it is easy to overlook... thanks for your help i truly appreciate it!

**Comment by spock123** [comment]
Hi @dweitz43 , I've managed to solved  your issues.
I made a new public repo containing your code, including the fixes. 

https://github.com/spock123/dweitz43-fixed

I'll try to summon some of the changes:

1. Overlay.css
I removed the loading in your webpack conf, and inserted the two css rules into your app.styles file instead. It's much easier that way. Remember to remove them once Material2 gets updated to the next version, as it will contain all style you will need.
I also removed it from your header-file in webpack. You should always load your css/scss in your code, so that it becomes part of your bundles. Otherwise, you will need to copy assets, and your browser will need http request to get the extra files.
I have removed the overlay.css loading  in that file, as it is no longer needed after the fix.

2. Loading styles not needed
You don't need to load any Material2 styles - they are included in the modules. 

3. Hammer.js
Some of the Material2 modules require the library hammer.js to be installed.
I have installed it and it is loaded in the vendors file.

4. ngModules
Remember that "pipes" and "directives" properties in your components are deprecated. All directives and pipes need to be decared in your modules, not in your components. I have removed the properties from your home.component and imported them in the app module.

5. Angular2 RC5 bug - workaround
There is a bug in Angular2 RC5 that can cause the build to crash.
The temporary workaround is to set mangle to false in your webpack.production configuration.
I have updated your configuration so that it works.

Hope this helps you along

I have tested production build and it works fine now.

**Comment by dweitz43** [comment]
@spock123 wow, thank you so much! I believe i realize my mistakes now, your explanation is very clear! Finally I think I can create the pr to update the original angular2-webpack-starter material2 branch, thanks to your help! i was definitely lost on this, i cannot express my gratitude enough for your effort!

**Comment by spock123** [comment]
@dweitz43  no worries, it was a pleasure... :) 

Now I'm going to get drunk, hehe.. have a nice evening (it's 20.08 here)
Cheers
